---
title: "Flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
```

```{r}
data("rest_inspec")

rest_inspec = 
  rest_inspec |> 
  mutate(
    inspection_year = year(inspection_date)
  ) |> 
  select(
    boro, cuisine_description, score, critical_flag,
    inspection_date, inspection_year, latitude, longitude
  ) |> 
  filter(
    cuisine_description == "Chinese",
    latitude != 0,
    longitude != 0, 
    score >= 0,
    score <= 30,
    inspection_year == 2019
  )
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
rest_inspec |> 
  mutate(
    label = str_c("Score: ", score, "\nBorough: ", boro) 
  ) |> 
  plot_ly(
    x = ~longitude, y = ~latitude, color = ~score,
    text = ~label, 
    type = "scatter", mode = "markers", alpha = 0.5
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
rest_inspec |> 
  mutate(
    boro = fct_reorder(boro, score)
  ) |> 
  plot_ly(
    x = ~boro, y = ~score, color = ~boro,
    type = "box", colors = "viridis"
  )
```

### Chart C

```{r}
rest_inspec |> 
  count(boro) |> 
  rename(restaurant_count = n) |>
  mutate(
    boro = fct_reorder(boro, restaurant_count)
  ) |> 
  plot_ly(
    x = ~boro, y = ~restaurant_count,
    type = "bar")
```

